using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System.IO;
using TMPro;
using UnityEngine.SceneManagement;

public class RunMapEdited : MonoBehaviour
{
    [SerializeField] private InformationsForEditMap salle1;
    [SerializeField] private InformationsForEditMap salle2; 
    [SerializeField] private InformationsForEditMap salle3; 
    [SerializeField] private InformationsForEditMap salle4; 
    [SerializeField] private InformationsForEditMap salle5; 
    [SerializeField] private InformationsForEditMap salle6; 
    [SerializeField] private InformationsForEditMap salle7; 
    [SerializeField] private InformationsForEditMap salle8; 
    [SerializeField] private InformationsForEditMap salle9; 
    [SerializeField] private InformationsForEditMap salle10; 
    [SerializeField] private InformationsForEditMap salle11; 
    [SerializeField] private InformationsForEditMap salle12; 
    [SerializeField] private InformationsForEditMap salle13; 
    [SerializeField] private InformationsForEditMap salle14; 
    [SerializeField] private InformationsForEditMap salle15; 
    [SerializeField] private GameObject numberOfSalle;
    private string chemin, jsonString;
    public string scene;


    public void RunEditionMap() {
        salle1.GetNumberOfEnemy();
        salle2.GetNumberOfEnemy();
        salle3.GetNumberOfEnemy();
        salle4.GetNumberOfEnemy();
        salle5.GetNumberOfEnemy();
        salle6.GetNumberOfEnemy();
        salle7.GetNumberOfEnemy();
        salle8.GetNumberOfEnemy();
        salle9.GetNumberOfEnemy();
        salle10.GetNumberOfEnemy();
        salle11.GetNumberOfEnemy();
        salle12.GetNumberOfEnemy();
        salle13.GetNumberOfEnemy();
        salle14.GetNumberOfEnemy();
        salle15.GetNumberOfEnemy();
        chemin = Application.streamingAssetsPath + "/EditeurMap.json";
        jsonString = File.ReadAllText(chemin);
        VariableJSON editionMap = JsonUtility.FromJson<VariableJSON>(jsonString);
        editionMap.nb_salles = int.Parse(numberOfSalle.GetComponent<TMP_InputField>().text);
        editionMap.type_salle_1 = salle1.typeSalle;
        editionMap.nb_pit_1 = salle1.numberPit;
        editionMap.nb_pat_1 = salle1.numberPat;
        editionMap.nb_pot_1 = salle1.numberPot;
        editionMap.nb_put_1 = salle1.numberPut;
        editionMap.type_salle_2 = salle2.typeSalle;
        editionMap.nb_pit_2 = salle2.numberPit;
        editionMap.nb_pat_2 = salle2.numberPat;
        editionMap.nb_pot_2 = salle2.numberPot;
        editionMap.nb_put_2 = salle2.numberPut;
        editionMap.type_salle_3 = salle3.typeSalle;
        editionMap.nb_pit_3 = salle3.numberPit;
        editionMap.nb_pat_3 = salle3.numberPat;
        editionMap.nb_pot_3 = salle3.numberPot;
        editionMap.nb_put_3 = salle3.numberPut;
        editionMap.type_salle_4 = salle4.typeSalle;
        editionMap.nb_pit_4 = salle4.numberPit;
        editionMap.nb_pat_4 = salle4.numberPat;
        editionMap.nb_pot_4 = salle4.numberPot;
        editionMap.nb_put_4 = salle4.numberPut;
        editionMap.type_salle_5 = salle5.typeSalle;
        editionMap.nb_pit_5 = salle5.numberPit;
        editionMap.nb_pat_5 = salle5.numberPat;
        editionMap.nb_pot_5 = salle5.numberPot;
        editionMap.nb_put_5 = salle5.numberPut;
        editionMap.type_salle_6 = salle6.typeSalle;
        editionMap.nb_pit_6 = salle6.numberPit;
        editionMap.nb_pat_6 = salle6.numberPat;
        editionMap.nb_pot_6 = salle6.numberPot;
        editionMap.nb_put_6 = salle6.numberPut;
        editionMap.type_salle_7 = salle7.typeSalle;
        editionMap.nb_pit_7 = salle7.numberPit;
        editionMap.nb_pat_7 = salle7.numberPat;
        editionMap.nb_pot_7 = salle7.numberPot;
        editionMap.nb_put_7 = salle7.numberPut;
        editionMap.type_salle_8 = salle8.typeSalle;
        editionMap.nb_pit_8 = salle8.numberPit;
        editionMap.nb_pat_8 = salle8.numberPat;
        editionMap.nb_pot_8 = salle8.numberPot;
        editionMap.nb_put_8 = salle8.numberPut;
        editionMap.type_salle_9 = salle9.typeSalle;
        editionMap.nb_pit_9 = salle9.numberPit;
        editionMap.nb_pat_9 = salle9.numberPat;
        editionMap.nb_pot_9 = salle9.numberPot;
        editionMap.nb_put_9 = salle9.numberPut;
        editionMap.type_salle_10 = salle10.typeSalle;
        editionMap.nb_pit_10 = salle10.numberPit;
        editionMap.nb_pat_10 = salle10.numberPat;
        editionMap.nb_pot_10 = salle10.numberPot;
        editionMap.nb_put_10 = salle10.numberPut;
        editionMap.type_salle_11 = salle11.typeSalle;
        editionMap.nb_pit_11 = salle11.numberPit;
        editionMap.nb_pat_11 = salle11.numberPat;
        editionMap.nb_pot_11 = salle11.numberPot;
        editionMap.nb_put_11 = salle11.numberPut;
        editionMap.type_salle_12 = salle12.typeSalle;
        editionMap.nb_pit_12 = salle12.numberPit;
        editionMap.nb_pat_12 = salle12.numberPat;
        editionMap.nb_pot_12 = salle12.numberPot;
        editionMap.nb_put_12 = salle12.numberPut;
        editionMap.type_salle_13 = salle13.typeSalle;
        editionMap.nb_pit_13 = salle13.numberPit;
        editionMap.nb_pat_13 = salle13.numberPat;
        editionMap.nb_pot_13 = salle13.numberPot;
        editionMap.nb_put_13 = salle13.numberPut;
        editionMap.type_salle_14 = salle14.typeSalle;
        editionMap.nb_pit_14 = salle14.numberPit;
        editionMap.nb_pat_14 = salle14.numberPat;
        editionMap.nb_pot_14 = salle14.numberPot;
        editionMap.nb_put_14 = salle14.numberPut;
        editionMap.type_salle_15 = salle15.typeSalle;
        editionMap.nb_pit_15 = salle15.numberPit;
        editionMap.nb_pat_15 = salle15.numberPat;
        editionMap.nb_pot_15 = salle15.numberPot;
        editionMap.nb_put_15 = salle15.numberPut;
        jsonString = JsonUtility.ToJson(editionMap);
        File.WriteAllText(chemin, jsonString);
        SceneManager.LoadScene(scene);
    }

}